# Generated by Django 6.0.1 on 2026-04-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán mặc định'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='Màu sắc')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá cho màu này')),
                ('stock', models.IntegerField(default=0, verbose_name='Số lượng trong kho')),
                ('available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
            },
        ),
    ]
