# Generated by Django 6.0.1 on 2026-04-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã giảm giá')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Số tiền giảm (VND)')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link Video TikTok/YouTube'),
        ),
    ]
