# Generated by Django 6.0.1 on 2026-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productvariant_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
